# helm/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: {{ include "school-website.fullname" . }}
  labels:
    {{- include "school-website.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "school-website.selectorLabels" . | nindent 4 }}
