replicaCount: 1

image:
  repository: campus1.jfrtpt.org/docker/campus
  tag: latest-arm64
  pullPolicy: IfNotPresent

imagePullSecrets:
  - name: jfrog-secret

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: school.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: school-website-tls
      hosts:
        - school.example.com

nodeSelector:
  node.kubernetes.io/role: artifactory-service

tolerations:
  - key: dedicated
    operator: Equal
    value: artifactory-service
    effect: NoSchedule

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

affinity: {}