replicaCount: 1

frontend:
  enabled: true
  image:
    repository: campus0507.jfrtpt.org/docker/campus
    tag: "0607new"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 80
    targetPort: 80

backend:
  enabled: true
  image:
    repository: campus0507.jfrtpt.org/docker/campus-backend
    tag: "0607new"
    pullPolicy: Always
  service:
    type: ClusterIP
    port: 3001
    targetPort: 3001
  env:
    PORT: "3001"
    DB_HOST: "rds-campus0507.czkduehwi9ml.eu-central-1.rds.amazonaws.com"
    DB_PORT: "5432"
    DB_NAME: "campus"
    DB_USER: "campus_admin"
    DB_PASSWORD: "school_password_2025"
    JWT_SECRET: "your-super-secret-jwt-key-change-in-production-2025"
    JWT_EXPIRY: "24h"
    FRONTEND_URL: "*"
    RATE_LIMIT_WINDOW_MS: "900000"
    RATE_LIMIT_MAX_REQUESTS: "1000"

imagePullSecrets:
  - name: jfrog-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: school.example.com
  tls:
    - secretName: school-website-tls
      hosts:
        - school.example.com

resources:
  frontend:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  backend:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

nodeSelector:
  node.kubernetes.io/role: artifactory-service

tolerations:
  - key: dedicated
    operator: Equal
    value: artifactory-service
    effect: NoSchedule

affinity: {}
